spring:
  datasource:
    url: jdbc:mysql://192.168.1.204:3306/myscdb2-5?userUnicode=true&characterEncoding=utf-8
    username: root
    password: myzh1234
#    url: jdbc:mysql://www.yidab.com:61003/myscdb2-5-pre-4?userUnicode=true&characterEncoding=utf-8
#    username: myscdb2_pre
#    password: myscdb2preYDB